databases:
  - name: search
    databaseName: search_52zr
    user: search_52zr_user

services:
  - type: web
    name: torre-search-backend
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: search_52zr
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false